#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

#/ Description: cleans, builds, tests, and documents all rust project files
#/ Usage: make
#/ Options:
#/   --help: Display this help message
usage() { grep '^#/' "$0" | cut -c4- ; exit 0 ; }
expr "$*" : ".*--help" > /dev/null && usage

readonly LOG_FILE="/tmp/$(basename "$0").log"
info()    { echo "[INFO]    $*" | tee -a "$LOG_FILE" >&2 ; }
warning() { echo "[WARNING] $*" | tee -a "$LOG_FILE" >&2 ; }
error()   { echo "[ERROR]   $*" | tee -a "$LOG_FILE" >&2 ; }
fatal()   { echo "[FATAL]   $*" | tee -a "$LOG_FILE" >&2 ; exit 1 ; }

cleanup() {
    # Remove temporary files
    # Restart services
    # ...
    echo ''	# add dummy command to keep shellcheck from complaining
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
    trap cleanup EXIT

    printf "\n"
    cargo clean
    cargo test
    printf "generating rust doc's\r"
    rustdoc src/lib.rs
    rustdoc src/greetings/english.rs
    rustdoc src/greetings/french.rs
    printf "                     \rfinished.\n"
fi
